Feature/add fraud payload
w-pay/sdk-wpay-js pull request #1
Opened 2021-07-02 07:07 UTC by jameskeating87

2021-07-06 00:30 UTC, kierans requested changes
Good job @jameskeating87 !

Few points to touch up. You should also update the README with the new spec version number.

2021-07-06 00:30 UTC, kierans commented on src/api/customer-payment-agreements.js
>  // create :: HttpApiClient -> (CreatePaymentAgreementRequest, [ChallengeResponse]?) -> Promise PaymentAgreements
Probably should be consistent with the type signatures across the codebase. Even if that means removing them. 🤔

2021-07-06 00:30 UTC, kierans commented on package.json
> +  "version": "1.5.1",
Rather than a patch, this should be a minor bump I think due to signature changes.

2021-07-06 00:30 UTC, kierans commented on test/matchers/payment-meta-matchers.js
> +            assertThat(actual, is(challengeResponsesDTOFrom(challengeResponses)));
Why didn't prettier fix this indentation?

2021-07-06 00:32 UTC, kierans commented
Need to also regen the docs at the moment.

2021-07-06 02:29 UTC, kierans requested changes
I think we need the update to `package-lock.json`.

2021-07-06 02:29 UTC, kierans commented on README.md
> +The SDK currently supports version 1.0.5 of the API spec.
👍

2021-07-06 02:29 UTC, kierans commented on package.json
> +  "version": "1.6.0",
Shouldn't the `package-lock.json` be included?

Did you use `npm version` to bump the version?

**Note**: If using `npm version` pull my merge from main. It contains NPM config to prevent git tagging the branch.

2021-07-06 02:33 UTC, kierans commented
@jameskeating87 You might want to run `npm run format` and see what changes Prettier makes.

While I don't oppose formatting style like the ones you've made with multiple function args (as in my opinion it makes the code more readable) you should add "disable prettier" comments to stop prettier reformatting the blocks.

This is a consequence of using an opinionated formatter like Prettier.

2021-07-06 04:19 UTC, jameskeating87 commented
@kierans  I've now running prettier. I thought there was something wrong with my settings because it was changing every file in the repo. Turns out it was just the end of line formatting. I assume this is a product of the fact that I'm working on Windows and you're on Mac.

2021-07-06 06:12 UTC, kierans approved these changes

2021-07-11 23:51 UTC, kierans commented
@jameskeating87 Should this be merged now? Can client apps use the new functionality?

2021-07-23 06:46 UTC, jameskeating87 commented
@kierans If you're happy with the change I'll merge it now. The changes have been made in the wallet service but I wouldn't be in production yet. However, the fraud payload is optional so there shouldn't be any issues. It would just be ignored until those changes are deployed.

2021-07-26 03:22 UTC, kierans commented
@jameskeating87 I think it should be OK. If the consuming app doesn't want to target the 1.0.5 version of the spec, they can just use previous versions of the SDK (which is why we bumped the minor version of the module).

2021-07-27 06:07 UTC, merged